In [1]:
import tensorflow as tf
import numpy as np
from tfRegression import TfRegression

In [2]:
n_sample = 1000
learning_rate=0.01
num_epochs=100
random_X = np.random.normal(size=(n_sample, 4))
random_Y = np.random.normal(size=(n_sample, 1))
w =tf.Variable(tf.random_normal((5, 1), name="weight", dtype=tf.float64))


Instructions for updating:
Colocations handled automatically by placer.


In [4]:
for x, y in next_batch(random_X, random_Y, 100):
    print(x, y)

[[ 1.1885987  -1.40737931  2.0641575   1.0138826 ]
 [-0.11370368  0.6439453  -0.48540278 -1.49922149]
 [ 0.48427237 -0.73893007  0.49044875  0.30454752]
 [ 0.4710296  -0.85813472  0.13635899  0.81753019]
 [-1.23766728 -0.92566707 -0.39495143  0.19591808]
 [-0.21528698  0.24312599 -0.21282807 -0.93726114]
 [-1.34308317  0.57104854  0.66599149 -1.05832692]
 [ 1.2795927   0.20467789 -2.03189792  2.09946699]
 [ 0.0468659  -0.58497659 -0.89686713  1.61925   ]
 [-0.30961875 -1.4271405  -1.51596147  0.61993557]
 [-1.34568312 -0.78859345 -0.87852452 -0.83796336]
 [ 1.00468994  0.91898378  0.99951773 -0.00322218]
 [-1.41952992 -0.47439864 -0.28493097  1.2326097 ]
 [-0.61032976 -0.68470794  0.07662433  0.74335113]
 [-0.01926179 -0.53836667 -0.4747369   1.2385279 ]
 [ 1.04542928  2.38448114  0.47691667 -1.00961991]
 [-0.72673643 -1.59980484 -0.02189184  0.20150864]
 [ 1.95256869  0.73758886  0.2057945  -2.15711803]
 [ 0.44316167  1.57761226  0.94562103  1.79433747]
 [ 1.37974463  0.93743491 -0.07

 [-1.21578949e+00 -1.12183348e+00  6.01375481e-01  4.48290866e-01]] [[ 0.94223084]
 [ 1.44975378]
 [ 0.27069458]
 [ 1.27799698]
 [-0.34999196]
 [ 1.70747621]
 [ 0.81771154]
 [ 0.09103242]
 [ 0.39019767]
 [ 1.17965017]
 [ 0.78673174]
 [ 0.71207211]
 [-0.1644639 ]
 [-0.19216452]
 [-1.59345343]
 [ 1.05757121]
 [-0.48051315]
 [-0.88931837]
 [ 0.62110106]
 [-0.87164805]
 [ 0.09736864]
 [-0.74745204]
 [ 0.33157389]
 [ 0.16599809]
 [-0.50337598]
 [-2.00579455]
 [-2.25622532]
 [ 0.72346577]
 [-0.91088153]
 [ 1.7020204 ]
 [-0.02499551]
 [-1.69229962]
 [-0.94812763]
 [-0.86543271]
 [ 1.3268629 ]
 [ 0.11412785]
 [ 0.24936207]
 [ 0.50914447]
 [-0.88742074]
 [ 0.24277758]
 [ 0.90605791]
 [ 2.07371823]
 [ 1.33343617]
 [-0.88690857]
 [-0.35864104]
 [ 0.32976104]
 [-0.20050126]
 [-0.25807455]
 [-1.02448973]
 [-0.42266819]
 [ 0.06247453]
 [ 0.18525496]
 [-0.42951738]
 [ 0.42214477]
 [-0.76075111]
 [-1.59705233]
 [ 0.44689027]
 [ 0.55546688]
 [-1.36635912]
 [ 0.6436779 ]
 [-0.99145643]
 [ 0.19090782]
 [

In [5]:
regression = TfRegression(inputs=random_X, output= random_Y)

In [13]:
init = tf.global_variables_initializer()
x_ = tf.placeholder(tf.float32, shape=[None, 4 + 1])
y_ = tf.placeholder(tf.float32, shape=[None, 1])


inputs_ = regression.append_bias(random_X)
w = tf.Variable(tf.random_normal((4 + 1, 1),
                                         name="weight", dtype=tf.float64))


y_pred= regression.model(inputs_, w)
mse = tf.reduce_mean(tf.square(random_Y - y_pred))
optimizer = tf.train.GradientDescentOptimizer(
    learning_rate)
train_op = optimizer.minimize(mse)

cost_trace = []
with tf.Session() as sess:
    # Setup a session & initialize all variables
    sess.run(tf.global_variables_initializer())
    for i in range(num_epochs):
        for x_batch, y_batch in next_batch(random_X, random_Y, 100):
            x_batch_plus_intercept = regression.append_bias(x_batch)
            
            cost_trace.append(sess.run(mse, feed_dict={x_: x_batch_plus_intercept, y_: y_batch}))
            sess.run(train_op, feed_dict={x_: x_batch_plus_intercept, y_: y_batch})
    print(w.eval())

[[ 0.02388925]
 [-0.03010949]
 [ 0.01538141]
 [ 0.03900917]
 [ 0.00800283]]


In [9]:
cost_trace

[12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
 12.68820975863503,
